### ISSUE TITLE
Grundfunktionalität

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-ratebutton#2]
Mit Hilfe eines Shortcodes soll in Seiten, Artikeln oder anderen Texteingabefeldern, die Shortcodes ausführen können, ein bzw mehrere Buttons eingefügt werden.
Diese Buttons sollen einen Zähler darstellen, der schlicht anzeigt, wie oft auf den jeweiligen Button geklickt wurde.

Eine ähnliche Funktionalität bietet dieses Plugin:  https://likebtn.com/en/wordpress-like-button-plugin

Buttons können Up/Downvotes darstellen. HIerbei sollte aber aus Performancegründen entweder nur ein kleines Set an SVG-Icons bereitgestellt werden oder aber, wenn das FAU Design verwendet wird, das dort bereits geladende AwesomeFont genutzt werden.

Der Klick der Buttons wird **nicht via Identifikation der Benutzer gesichert**. Hier wird der Datensparsamkeit und dem Datenschutz der Nutzer Vorrang gegenüber der SIcherheit der Zähler gegeben.
Auch soll die IP **nicht** gespeichert werden. Somit ist kein Schutz gegen Mehrfach-KLicks vorgesehen. Via Option jedoch sollte ein Speichern in einem Cookie möglich sein, welcher lediglich feststellt, dass man bereits geklickt hat.

**Comment by rvdforst** [comment]
Anforderungen erfüllt.
