### ISSUE TITLE
Rate-Buttons über Shortcode 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-ratebutton#4]
Je Button soll die Optik (das Symbol über ein Attributfestgelegt werden. Der Ratecounter soll an der zu vergebenden Id des Buttons gebunden sein, nicht an dem Symbol.
In einer Seite oder einem Post soll derselbe Button auch mehrmals vorkommen können und auch verschiedene andere Buttons vorhanden sein können.

Der Shortcode soll also mindestens folgende Attribute haben:
- id=""
- symbol=""

Also z.B. so:
     `[ratebutton id="111" symbol="thumbup"]`

Wenn kein Symbol gegeben ist, soll ein Default-Symbol verwendet werden.  
Die Liste der verfügbaren Symbole ist zu definieren, sie ist aber zu limitieren.
Wenn die FAU Designs verwendet werden, ist optional auf das AwesomeFont Set zurückzugreifen.
Alternativ sind Symbole als SVG bereitzustellen.

**Comment by rvdforst** [comment]
In der Version 1.0.0 hat der Shortcode keine Parameter. Es ist vorerst nicht geplant, dass das Plugin weiter entwickelt wird.
Shortcode-Ausgabe:
<img width="112" alt="bildschirmfoto 2019-01-18 um 16 26 03" src="https://user-images.githubusercontent.com/299916/52217028-e80f4b80-2897-11e9-9ca3-16425809f28b.png">
