### ISSUE TITLE
Rate-Button Symbole

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-ratebutton#5]
Folgende Symbole sollten mindestens vorhanden sein:

- Thumbs Up
- Thumps Down
- Pfeil Up
- Pfeil Down
- Plus / Positiv / Gut
- Minus / Negativ / Schlecht
- Sterne-Rating: 1 bis 5 Sterne, je ein Button 

vgl auch https://fontawesome.com/icons?d=gallery

**Comment by rvdforst** [comment]
Siehe https://github.com/RRZE-Webteam/rrze-ratebutton/issues/4
